apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-grunndata-media
  namespace: teamdigihot
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  labels:
    team: teamdigihot
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  replicas:
    min: {{min_replicas}}
    max: {{max_replicas}}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1536Mi
    requests:
      cpu: 200m
      memory: 128Mi
  prometheus:
    enabled: true
    path: /internal/prometheus
  leaderElection: true
  filesFrom:
    - secret: hm-grunndata-media-credentials
      mountPath: /var/run/secrets/credentials/hm-grunndata-media
  env:
    - name: DB_DRIVER
      value: "org.postgresql.Driver"
    - name: DB_JDBC_URL
      value: "jdbc:postgresql://${DB_HOST}:5432/media"
    - name: RAPIDSANDRIVERS_ENABLED
      value: "{{ rapidsandrivers_enabled }}"
    - name: SCHEDULERS_ENABLED
      value: "{{ schedulers_enabled }}"
    - name: GCP_BUCKET_NAME
      value: "{{ bucket_name }}"
    - name: MEDIA_STORAGE_ENABLED
      value: "{{ media_storage_enabled }}"
    - name: GCP_CREDENTIALS_LOCATION
      value: "/var/run/secrets/credentials/hm-grunndata-media/secret"
    - name: MEDIA_STORAGE_CDNURL
      value: "{{ media_storage_cdnurl }}"
    - name: JAVA_OPTS
      value: "{{java_opts}}"
  gcp:
    sqlInstances:
      - name: hm-grunndata-media
        type: POSTGRES_14
        tier: {{disk_tier}}
        diskType: SSD
        highAvailability: true
        diskSize: {{disk_size}}
        diskAutoresize: true
        autoBackupTime: "03:00"
        databases:
          - name: media
            envVarPrefix: DB
        cascadingDelete: false
    buckets:
      - name: {{bucket_name}}
  kafka:
    pool: {{kafka_cluster}}
  accessPolicy:
    outbound:
      external:
        - host: www.hjelpemiddeldatabasen.no
      rules:
        - application: hm-grunndata-db
    inbound:
      rules:
        - application: hm-grunndata-register
