micronaut:
  server:
    multipart:
      max-file-size: 10097152
    port: ${SERVER_PORT:8080}
  object-storage:
    gcp:
      default:
        bucket: ${GCP_BUCKET_NAME:}
  application:
    name: hm-grunndata-media
    thread-selection: auto
  executors:
    consumer:
      type: fixed
      nThreads: 1
  metrics:
    enabled: true
    binders:
      uptime:
        enabled: true
      processor:
        enabled: true
      jvm:
        enabled: true
      web:
        enabled: true
      logback:
        enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
endpoints:
  metrics:
    enabled: true
  prometheus:
    sensitive: false
    enabled: true
  all:
    path: "/internal"

jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true

datasources:
  default:
    url: ${DB_JDBC_URL:`jdbc:tc:postgresql:14:///gdb?TC_TMPFS=/testtmpfs:rw&TC_INITSCRIPT=file:src/test/resources/postgres/postgres-init.sql&TC_REUSABLE=true`}
    driverClassName: ${DB_DRIVER:org.testcontainers.jdbc.ContainerDatabaseDriver}
    username: ${DB_USERNAME:media}
    password: ${DB_PASSWORD:media}
    maximum-pool-size: 8
    minimum-idle: 0
    pool-name: default

flyway:
  datasources:
    default:
      locations: classpath:db

# Rapids and rivers config
rapidsandrivers:
  enabled: ${RAPIDSANDRIVERS_ENABLED:false}

kafka:
  topic: teamdigihot.hm-grunndata-v1
  consumerGroupId: hm-grunndata-media-g1
  trustStorePath: ${KAFKA_TRUSTSTORE_PATH:}
  trustStorePassword: ${KAFKA_CREDSTORE_PASSWORD:}
  keystorePath: ${KAFKA_KEYSTORE_PATH:}
  keystorePassword: ${KAFKA_CREDSTORE_PASSWORD:}
  health:
    enabled: false

gcp:
  project-id:
  credentials:
    location: ${GCP_CREDENTIALS_LOCATION:/path/to/credential}
media:
  storage:
    enabled: ${MEDIA_STORAGE_ENABLED:false}
    retention: ${MEDIA_STORAGE_RETENTION:180d}
    cdnurl: ${MEDIA_STORAGE_CDNURL:`http://localhost:8081/local`}

schedulers:
  enabled: ${SCHEDULERS_ENABLED:false}

elector:
  path: ${ELECTOR_PATH:localhost}


